from app.models.monster import Monster
from sqlalchemy import select
from sqlalchemy.orm import Session

SEED_MONSTERS = [
    {
        "id": 1,
        "slug": "tharvok",
        "name": "Tharvok",
        "title": "Guerreiro da Brasa Rubra",
        "description": "Um felino colossal em armadura negra incandescente que avanca como um ariete em meio ao fogo vivo.",
        "lore": "Nascido entre metal, cinza e magma, Tharvok transforma furia em impacto bruto e domina a linha de frente com presenca avassaladora.",
        "card_type": "Berserker",
        "attribute": "Chama",
        "rarity": 5,
        "level": 4,
        "attack": 1800,
        "defense": 2500,
        "health": 3400,
        "mana_cost": 4,
        "primary_color": "#C93F1F",
        "secondary_color": "#FF6B2D",
        "image_path": "/assets/monsters/Tharvok.png",
        "ability_name": "Frenesi da Brasa",
        "ability_text": "Aumenta permanentemente o proprio ATK em 50% e reduz a DEF atual a 0. Nao pode ser reaplicada.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "duel",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 2,
        "slug": "velkryon",
        "name": "Drakoryn",
        "title": "Bastiao do Geodo Dourado",
        "description": "Uma besta colossal de pelagem cinzenta e armadura rochosa atravessada por fissuras douradas de energia.",
        "lore": "Drakoryn protege o campo como uma fortaleza viva, absorvendo impacto e respondendo com golpes pesados alimentados por energia ancestral.",
        "card_type": "Guardiao",
        "attribute": "Terra Solar",
        "rarity": 5,
        "level": 4,
        "attack": 2700,
        "defense": 3100,
        "health": 3600,
        "mana_cost": 4,
        "primary_color": "#C99944",
        "secondary_color": "#F7C96A",
        "image_path": "/assets/monsters/Velkryon.png",
        "ability_name": "Coracao de Geodo",
        "ability_text": "Dobra a propria vida maxima e a vida atual uma unica vez no duelo. Apos usar, nao pode atacar neste turno.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "duel",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 3,
        "slug": "skhar",
        "name": "Skhar",
        "title": "Arlequim do Pesadelo",
        "description": "Um bufao demoniaco de sorriso cruel cercado por aparicoes distorcidas e fumaca de caos.",
        "lore": "Skhar brinca com o medo dos inimigos, surgindo entre gargalhadas sombrias para punir fragilidade e espalhar confusao no campo.",
        "card_type": "Trapaceiro",
        "attribute": "Caos",
        "rarity": 4,
        "level": 6,
        "attack": 2500,
        "defense": 1700,
        "health": 2200,
        "mana_cost": 5,
        "primary_color": "#8A2E2B",
        "secondary_color": "#5C3E78",
        "image_path": "/assets/monsters/Skhar.png",
        "ability_name": "Doppelganger",
        "ability_text": "Cria um clone em seu campo com 50% dos status atuais. O clone nasce sem poder usar habilidade.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 4,
        "slug": "morvhal",
        "name": "Morvhal",
        "title": "Carrasco da Lua Azul",
        "description": "Uma criatura esqueletica felina envolta por chamas lunares azuladas e presas espectrais.",
        "lore": "Morvhal vagueia entre ruinas e luar, avancando com agilidade fantasmagorica para corroer a resistencia dos vivos.",
        "card_type": "Espectro",
        "attribute": "Lua Sombria",
        "rarity": 4,
        "level": 6,
        "attack": 2300,
        "defense": 1800,
        "health": 2100,
        "mana_cost": 4,
        "primary_color": "#4FD7E7",
        "secondary_color": "#BFEFFF",
        "image_path": "/assets/monsters/Morvhal.png",
        "ability_name": "Manto da Lua Morta",
        "ability_text": "Uma vez por turno, nao pode ser alvo de ataques ate o fim do proximo turno e recebe +15% de ATK no turno atual.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 5,
        "slug": "dragao-pistola",
        "name": "Dragao Pistola",
        "title": "Executor da Garganta Trovejante",
        "description": "Um draco blindado com maxilares de canhao e costelas de bronze recarregadas por runas de combustao.",
        "lore": "Criado nas furnas de Boca de Ferrum, so desperta quando um cerco precisa terminar em um unico estampido sagrado.",
        "card_type": "Draconoide",
        "attribute": "Fogo Belico",
        "rarity": 5,
        "level": 9,
        "attack": 2900,
        "defense": 2100,
        "health": 3000,
        "mana_cost": 10,
        "primary_color": "#A84A2A",
        "secondary_color": "#E0B36B",
        "image_path": "/assets/monsters/Dragao-Pistola.png",
        "ability_name": "Veredito de Balao",
        "ability_text": "1x por turno, destroi 1 carta no campo. Depois do disparo, esta carta nao pode atacar neste turno.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 6,
        "slug": "cartomante-do-fio-nulo",
        "name": "Cartomante do Fio Nulo",
        "title": "Contadora de Pressagios",
        "description": "Uma vidente ritual que costura cartas, cordoes e juramentos para manipular o fluxo do duelo.",
        "lore": "As Cartomantes da Escadaria de Odris nao preveem o futuro; elas calculam o preco para que ele aconteca.",
        "card_type": "Mistica",
        "attribute": "Arcano",
        "rarity": 3,
        "level": 4,
        "attack": 900,
        "defense": 1400,
        "health": 1500,
        "mana_cost": 4,
        "primary_color": "#D8D1BA",
        "secondary_color": "#355A7A",
        "image_path": "/assets/monsters/Cartomante-do-Fio-Nulo.png",
        "ability_name": "Contagem da Mesa",
        "ability_text": "Gera 1 de elixir para cada monstro em campo, ate 6. Se gerar 4 ou mais, esta carta nao pode atacar neste turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 7,
        "slug": "cervo-de-aurivau",
        "name": "Cervo de Aurivau",
        "title": "Arauto do Veio Dourado",
        "description": "Uma besta mineral de galhadas talhadas em geodo que sustenta aliados como um altar movente.",
        "lore": "Onde pisa, o chao vibra com as memorias dos guardioes soterrados.",
        "card_type": "Guardiao",
        "attribute": "Terra Solar",
        "rarity": 4,
        "level": 6,
        "attack": 1700,
        "defense": 2400,
        "health": 2800,
        "mana_cost": 6,
        "primary_color": "#8A7E67",
        "secondary_color": "#E6C76A",
        "image_path": "/assets/monsters/Cervo-de-Aurivau.png",
        "ability_name": "Antifona Mineral",
        "ability_text": "Escolha 1 carta aliada; ela recupera 300 de HP e ganha 400 de DEF ate o fim do proximo turno. Se ja estiver em defesa, recebe tambem 200 de ATK neste turno.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "ally_card",
    },
    {
        "id": 8,
        "slug": "midas-aureo",
        "name": "Midas, o Aureo",
        "title": "Rei do Toque Dourado",
        "description": "Um soberano amaldicoado cuja pele reluz como ouro vivo, capaz de transformar aliados e inimigos em reliquias resplandecentes.",
        "lore": "Ultimo regente do Abismo de Aurivau, Midas trocou pulso por eternidade e passou a governar uma corte de estatuas e juramentos fossilizados.",
        "card_type": "Guardiao",
        "attribute": "Luz Terrena",
        "rarity": 4,
        "level": 4,
        "attack": 1900,
        "defense": 2100,
        "health": 2600,
        "mana_cost": 6,
        "primary_color": "#C9A227",
        "secondary_color": "#FFD700",
        "image_path": "/assets/monsters/Midas-Aureo.png",
        "ability_name": "Toque de Ouro",
        "ability_text": "Escolha 1 carta no campo; ela fica com 1 de vida e dobra o proprio ATK ate o fim do proximo turno. Se for aliada, nao pode ser destruida neste turno; se for inimiga, nao pode atacar no proximo turno.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 9,
        "slug": "irma-da-vela-oca",
        "name": "Irma da Vela Oca",
        "title": "Novica da Cinza Serena",
        "description": "Uma monja carbonizada que vela ruinas e reata carne a partir de brasas sagradas.",
        "lore": "As Irmas da Vela Oca aprenderam que a chama mais fiel e a que arde em silencio.",
        "card_type": "Cleriga",
        "attribute": "Chama",
        "rarity": 2,
        "level": 3,
        "attack": 800,
        "defense": 1500,
        "health": 1700,
        "mana_cost": 3,
        "primary_color": "#A44A39",
        "secondary_color": "#F0C38C",
        "image_path": "/assets/monsters/Irma-da-Vela-Oca.png",
        "ability_name": "Vigilia de Cinza",
        "ability_text": "Cura 500 de vida do jogador e restaura 400 de HP de uma carta aliada. Se o alvo estiver abaixo de metade da vida, gera 1 de elixir.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "ally_card",
    },
    {
        "id": 10,
        "slug": "feral-de-serelune",
        "name": "Feral de Serelune",
        "title": "Cacador da Mare Azul",
        "description": "Um predador espectral de ossos finos e chama fria, feito para perseguir alvos exaustos entre lapides partidas.",
        "lore": "Dizem que a mare da necropole sobe quando um Feral sente medo no sangue dos vivos.",
        "card_type": "Espectro",
        "attribute": "Lua Sombria",
        "rarity": 3,
        "level": 5,
        "attack": 1900,
        "defense": 1100,
        "health": 1800,
        "mana_cost": 4,
        "primary_color": "#5BD7E8",
        "secondary_color": "#D9F6FF",
        "image_path": "/assets/monsters/Feral-de-Serelune.png",
        "ability_name": "Rastro de Lua",
        "ability_text": "Causa 400 de dano a 1 inimigo. Se o alvo for uma carta, ela muda para ataque e perde 300 de DEF ate o fim do proximo turno.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card_or_player",
    },
    {
        "id": 11,
        "slug": "bobo-do-nono-rasgo",
        "name": "Bobo do Nono Rasgo",
        "title": "Riso Entre Espelhos",
        "description": "Um arauto do caos coberto de seda, sinos e mascaras rachadas que converte confusao em vantagem.",
        "lore": "Ninguem recorda se fala por si ou por aquilo que usa o seu rosto.",
        "card_type": "Trapaceiro",
        "attribute": "Caos",
        "rarity": 3,
        "level": 5,
        "attack": 1600,
        "defense": 1200,
        "health": 1700,
        "mana_cost": 4,
        "primary_color": "#7C2C39",
        "secondary_color": "#B08AD6",
        "image_path": "/assets/monsters/Bobo-do-Nono-Rasgo.png",
        "ability_name": "Troca de Mascara",
        "ability_text": "Escolha 2 cartas no campo; elas trocam de posicao de batalha. Se uma delas estiver em defesa, ambas perdem 300 de ATK ate o fim do proximo turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "two_cards",
    },
    {
        "id": 12,
        "slug": "corista-de-odris",
        "name": "Corista de Odris",
        "title": "Voz dos Debitos Sacros",
        "description": "Uma escriba cantora que entoa contas rituais para comprimir o custo da guerra.",
        "lore": "Na Catedra das Cartas Cegas, toda melodia e uma formula de cobranca.",
        "card_type": "Mistica",
        "attribute": "Arcano",
        "rarity": 2,
        "level": 3,
        "attack": 700,
        "defense": 1300,
        "health": 1200,
        "mana_cost": 3,
        "primary_color": "#C8C0A5",
        "secondary_color": "#6B84A0",
        "image_path": "/assets/monsters/Corista-de-Odris.png",
        "ability_name": "Liturgia de Desconto",
        "ability_text": "Gera 2 de elixir. Se voce controlar outra carta Arcana, gera +1 adicional.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 13,
        "slug": "mastim-da-forja-muda",
        "name": "Mastim da Forja Muda",
        "title": "Dente de Corrente",
        "description": "Um cao de guerra de ferro negro, sem latido, usado para travar avancos e prender alvos.",
        "lore": "As correntes em seu dorso pertenciam a um rei que tentou fugir da propria armadura.",
        "card_type": "Besta",
        "attribute": "Chama",
        "rarity": 3,
        "level": 4,
        "attack": 1400,
        "defense": 1600,
        "health": 1900,
        "mana_cost": 4,
        "primary_color": "#6D3A30",
        "secondary_color": "#D88F4B",
        "image_path": "/assets/monsters/Mastim-da-Forja-Muda.png",
        "ability_name": "Mordida de Grilhao",
        "ability_text": "O alvo inimigo muda imediatamente para defesa e perde 400 de DEF ate o fim do proximo turno. Se ja estiver em defesa, sofre 300 de dano adicional.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 14,
        "slug": "viuva-do-espelho-cego",
        "name": "Viuva do Espelho Cego",
        "title": "Noiva da Memoria Troca",
        "description": "Uma dama amaldicoada que veste luto em seda escura e carrega um espelho sem reflexo.",
        "lore": "Toda vez que a Viuva olha para um inimigo, alguma lembranca deixa de pertencer a ele.",
        "card_type": "Ilusionista",
        "attribute": "Caos",
        "rarity": 4,
        "level": 6,
        "attack": 1200,
        "defense": 1700,
        "health": 1600,
        "mana_cost": 5,
        "primary_color": "#4A2335",
        "secondary_color": "#C3B5E9",
        "image_path": "/assets/monsters/Viuva-do-Espelho-Cego.png",
        "ability_name": "Casca de Reflexo Vazio",
        "ability_text": "Dissipa aprimoramentos do alvo, reduz o HP atual dele para 50% arredondado para baixo e faz esta carta ganhar 300 de ATK ate o fim do turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 15,
        "slug": "cavaleiro-do-veio-partido",
        "name": "Cavaleiro do Veio Partido",
        "title": "Guarda do Selo Profundo",
        "description": "Um guardiao em armadura geologica que luta como muralha viva e pune ofensivas impensadas.",
        "lore": "Jurou nunca recuar, mesmo depois de o proprio corpo comecar a virar rocha.",
        "card_type": "Guardiao",
        "attribute": "Terra Solar",
        "rarity": 4,
        "level": 6,
        "attack": 1800,
        "defense": 2600,
        "health": 2900,
        "mana_cost": 6,
        "primary_color": "#7A756A",
        "secondary_color": "#DDBE69",
        "image_path": "/assets/monsters/Cavaleiro-do-Veio-Partido.png",
        "ability_name": "Parede de Lastro",
        "ability_text": "Assume modo de defesa, recupera 700 de HP e recebe 500 de DEF ate o fim do proximo turno. Se ja estava em defesa, gera 1 de elixir.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 16,
        "slug": "corvo-da-lapide-sem-nome",
        "name": "Corvo da Lapide Sem Nome",
        "title": "Beija-olhos da Vigilia",
        "description": "Uma ave necrolunar de plumagem cinza-azulada que fareja o fim antes da morte chegar.",
        "lore": "O corvo nao se alimenta de carne, mas de nomes esquecidos.",
        "card_type": "Besta",
        "attribute": "Lua Sombria",
        "rarity": 2,
        "level": 2,
        "attack": 1100,
        "defense": 700,
        "health": 1000,
        "mana_cost": 2,
        "primary_color": "#688EA7",
        "secondary_color": "#D6F4FF",
        "image_path": "/assets/monsters/Corvo-da-Lapide-Sem-Nome.png",
        "ability_name": "Pouso de Omen",
        "ability_text": "Gera 1 de elixir. Se houver ao menos 1 carta em defesa no campo, gera +1 adicional e esta carta recebe 200 de ATK neste turno.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "none",
    },
    {
        "id": 17,
        "slug": "prior-do-fogo-afogado",
        "name": "Prior do Fogo Afogado",
        "title": "Pregador da Chama Impossivel",
        "description": "Um sacerdote coberto por tecido molhado em breu e brasas que nunca se apagam.",
        "lore": "Seu culto nasceu quando uma chama tentou sobreviver debaixo d'agua e aprendeu a odiar o mundo.",
        "card_type": "Clerigo",
        "attribute": "Chama",
        "rarity": 4,
        "level": 6,
        "attack": 1500,
        "defense": 1400,
        "health": 2000,
        "mana_cost": 5,
        "primary_color": "#8F3E2C",
        "secondary_color": "#F1B16F",
        "image_path": "/assets/monsters/Prior-do-Fogo-Afogado.png",
        "ability_name": "Sermo Carbonico",
        "ability_text": "Causa 500 a todas as cartas no campo, inclusive aliadas. Cartas que sobreviverem perdem 300 de ATK ate o fim do proximo turno.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "all_cards",
    },
    {
        "id": 18,
        "slug": "rastejante-de-geodo",
        "name": "Rastejante de Geodo",
        "title": "Verme do Selo Vivo",
        "description": "Uma criatura mineral longa e pesada que remenda fendilhas no campo como se costurasse pedra.",
        "lore": "Alguns mineiros juram que os Rastejantes nao escavam. Eles fecham caminhos proibidos.",
        "card_type": "Colosso",
        "attribute": "Terra Solar",
        "rarity": 4,
        "level": 6,
        "attack": 1600,
        "defense": 2800,
        "health": 3200,
        "mana_cost": 6,
        "primary_color": "#6E6B61",
        "secondary_color": "#D7B85B",
        "image_path": "/assets/monsters/Rastejante-de-Geodo.png",
        "ability_name": "Costura de Fenda",
        "ability_text": "Escolha 1 carta aliada; ela muda para defesa, recupera 300 de HP e ganha 500 de DEF ate o fim do proximo turno.",
        "ability_elixir_cost": 1,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "ally_card",
    },
    {
        "id": 19,
        "slug": "duquista-sem-face",
        "name": "Duquista Sem Face",
        "title": "Campeao dos Bailes Fendidos",
        "description": "Um espadachim mascarado cuja face foi substituida por um vazio espelhado.",
        "lore": "Nos saloes do Rasgo Nono, perder o rosto e o preco da elegancia perfeita.",
        "card_type": "Duelista",
        "attribute": "Caos",
        "rarity": 4,
        "level": 7,
        "attack": 2400,
        "defense": 1500,
        "health": 2100,
        "mana_cost": 7,
        "primary_color": "#6B1E2E",
        "secondary_color": "#E4C475",
        "image_path": "/assets/monsters/Duquista-Sem-Face.png",
        "ability_name": "Etiqueta de Sangue",
        "ability_text": "Escolhe uma carta em ataque; ela e forcada para defesa e perde 500 de ATK ate o fim do proximo turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 20,
        "slug": "astrarca-do-cimo-partido",
        "name": "Astrarca do Cimo Partido",
        "title": "Oraculo da Escada Final",
        "description": "Um arconte magro envolto em pergaminhos celestes e laminas astrais apagadas.",
        "lore": "Le os ceus como quem consulta faturas de um deus insolvente.",
        "card_type": "Oraculo",
        "attribute": "Arcano",
        "rarity": 4,
        "level": 7,
        "attack": 2100,
        "defense": 1800,
        "health": 2200,
        "mana_cost": 7,
        "primary_color": "#BFC4C9",
        "secondary_color": "#5678A3",
        "image_path": "/assets/monsters/Astrarca-do-Cimo-Partido.png",
        "ability_name": "Calculo de Catastrofe",
        "ability_text": "Escolhe 1 inimigo; se ele tiver menos elixir que voce, sofre 900 de dano. Caso contrario, sofre 400 e perde 1 de elixir.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card_or_player",
    },
    {
        "id": 21,
        "slug": "canhoneiro-de-ferrum",
        "name": "Canhoneiro de Ferrum",
        "title": "Servo da Retomada Rubra",
        "description": "Um veterano de cerco com ombro de bronze e caldeira presa ao torax.",
        "lore": "Jura nunca disparar sem nomear o pecado do alvo.",
        "card_type": "Artilheiro",
        "attribute": "Fogo Belico",
        "rarity": 3,
        "level": 4,
        "attack": 1500,
        "defense": 900,
        "health": 1500,
        "mana_cost": 4,
        "primary_color": "#92513A",
        "secondary_color": "#C2A06C",
        "image_path": "/assets/monsters/Canhoneiro-de-Ferrum.png",
        "ability_name": "Bala de Ruina",
        "ability_text": "Causa 700 a uma carta em ataque. Se ela sobreviver, muda imediatamente para defesa e nao pode trocar de posicao no proximo turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "card",
    },
    {
        "id": 22,
        "slug": "guarda-luto-de-serelune",
        "name": "Guarda-Luto de Serelune",
        "title": "Porteiro da Necropole Sussurrante",
        "description": "Um guerreiro espectral de alabarda azul que marcha sem emitir passos.",
        "lore": "Nao defende os mortos; impede que os vivos saiam iguais de onde entraram.",
        "card_type": "Espectro",
        "attribute": "Lua Sombria",
        "rarity": 3,
        "level": 5,
        "attack": 1700,
        "defense": 2000,
        "health": 2300,
        "mana_cost": 5,
        "primary_color": "#57BFD9",
        "secondary_color": "#E4FBFF",
        "image_path": "/assets/monsters/Guarda-Luto-de-Serelune.png",
        "ability_name": "Vigia da Passagem",
        "ability_text": "Um alvo aliado muda imediatamente para defesa, recupera 700 de HP e ganha 300 de DEF ate o fim do proximo turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "ally_card",
    },
    {
        "id": 23,
        "slug": "abadesa-da-conta-partida",
        "name": "Abadesa da Conta Partida",
        "title": "Senhora das Taxas Sombrias",
        "description": "Uma superiora austera que manipula dividas rituais e faz o campo pagar por sua propria existencia.",
        "lore": "Dizem que toda guerra em Asterra termina em ruina porque alguem aceitou o credito da Abadesa.",
        "card_type": "Mistica",
        "attribute": "Arcano",
        "rarity": 3,
        "level": 5,
        "attack": 1000,
        "defense": 1900,
        "health": 1800,
        "mana_cost": 5,
        "primary_color": "#D6CFBC",
        "secondary_color": "#826F4C",
        "image_path": "/assets/monsters/Abadesa-da-Conta-Partida.png",
        "ability_name": "Taxacao Ritual",
        "ability_text": "O oponente perde 1 de elixir para cada 2 cartas no seu campo, arredondado para baixo. Minimo 1, maximo 3. Se perder 3, esta carta recebe 300 de ATK neste turno.",
        "ability_elixir_cost": 2,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "player",
    },
    {
        "id": 24,
        "slug": "arquiteto-do-selo-submerso",
        "name": "Arquiteto do Selo Submerso",
        "title": "Pedreiro da Queda Antiga",
        "description": "Um titere de pedra santa e coral fossilizado, capaz de remodelar o campo como se fosse tumba.",
        "lore": "Construiu muralhas contra um rei que ainda nao havia despertado.",
        "card_type": "Colosso",
        "attribute": "Terra Solar",
        "rarity": 5,
        "level": 8,
        "attack": 2000,
        "defense": 3000,
        "health": 3300,
        "mana_cost": 8,
        "primary_color": "#7B7D79",
        "secondary_color": "#D1B66C",
        "image_path": "/assets/monsters/Arquiteto-do-Selo-Submerso.png",
        "ability_name": "Trava de Abobada",
        "ability_text": "Ate 2 cartas inimigas mudam para defesa, sofrem 300 de dano e perdem 300 de ATK ate o fim do proximo turno.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "up_to_two_cards",
    },
    {
        "id": 25,
        "slug": "reina-do-coral-carbonico",
        "name": "Reina do Coral Carbonico",
        "title": "Matriarca das Chamas Abissais",
        "description": "Uma entidade regia feita de coral queimado, carapaca vulcanica e luz negra filtrada.",
        "lore": "Surge apenas quando o mar subterraneo encontra as furnas mais antigas do mundo.",
        "card_type": "Soberana",
        "attribute": "Chama Abissal",
        "rarity": 5,
        "level": 9,
        "attack": 2600,
        "defense": 2400,
        "health": 3100,
        "mana_cost": 9,
        "primary_color": "#A13B34",
        "secondary_color": "#6FD6DA",
        "image_path": "/assets/monsters/Reina-do-Coral-Carbonico.png",
        "ability_name": "Mare de Escoria",
        "ability_text": "Causa 600 a todas as cartas inimigas e cura a si mesma em 300 para cada inimigo sobrevivente. Cartas sobreviventes perdem 200 de DEF ate o fim do proximo turno.",
        "ability_elixir_cost": 3,
        "ability_limit_scope": "turn",
        "ability_limit_count": 1,
        "ability_target_mode": "all_enemy_cards",
    },
]


def seed_monsters(session: Session) -> None:
    existing_monsters_by_slug = {
        monster.slug: monster
        for monster in session.execute(select(Monster)).scalars().all()
    }
    existing_monsters_by_id = {
        monster.id: monster
        for monster in existing_monsters_by_slug.values()
    }

    for monster_data in SEED_MONSTERS:
        existing = existing_monsters_by_slug.get(monster_data["slug"])
        if existing is None:
            existing = existing_monsters_by_id.get(monster_data["id"])
        if existing is None:
            session.add(Monster(**monster_data))
            continue

        for key, value in monster_data.items():
            setattr(existing, key, value)

    session.commit()
